### ISSUE TITLE
我使用时报错了Error: The getter 'ForcePressGestureRecognizer' isn't defined for the class

### ISSUE THREAD

**Issue by twovs** [LiuC520/flutter_drag_scale#1]
The following _CompileTimeError was thrown building GestureDetector(dirty):
I/flutter ( 2850): 'package:flutter_drag_scale/core/custom_gesture_detector.dart': error: line 546 pos 16:
I/flutter ( 2850): file:///G:/flutter/.pub-cache/git/flutter_drag_scale-8a9fbd918bc0333216c7704342246b498c05a419/lib/core/custom_gesture_detector.dart:546:16:
I/flutter ( 2850): Error: The getter 'ForcePressGestureRecognizer' isn't defined for the class
I/flutter ( 2850): '#lib1::GestureDetector'.
I/flutter ( 2850): Try correcting the name to the name of an existing getter, or defining a getter or field named
I/flutter ( 2850): 'ForcePressGestureRecognizer'.
I/flutter ( 2850):       gestures[ForcePressGestureRecognizer] =
I/flutter ( 2850):                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
I/flutter ( 2850):       gestures[ForcePressGestureRecognizer] =
I/flutter ( 2850):                ^
I/flutter ( 2850): When the exception was thrown, this was the stack:
I/flutter ( 2850): #0      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774:28)
I/flutter ( 2850): #1      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter ( 2850): #2      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #3      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 2850): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 2850): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #20     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 2850): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 2850): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 2850): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #56     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4047:11)
I/flutter ( 2850): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #58     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4965:32)
I/flutter ( 2850): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #63     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #64     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 2850): #65     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #71     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #77     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 2850): #78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #81     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 2850): #82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #86     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #87     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #90     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 2850): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #96     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 2850): #97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #102    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #103    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 2850): #104    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #108    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #109    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #110    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #114    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #120    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #121    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #122    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 2850): #123    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #124    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #127    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #128    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #129    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 2850): #130    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): #131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2850): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2850): #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2850): #134    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #135    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): #136    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2850): Error caught by widgets library, thrown building GestureDetector(dirty).
I/flutter ( 2850): 'package:flutter_drag_scale/core/custom_gesture_detector.dart': error: line 546 pos 16: file:///G:/flutter/.pub-cache/git/flutter_drag_scale-8a9fbd918bc0333216c7704342246b498c05a419/lib/core/custom_gesture_detector.dart:546:16: Error: The getter 'ForcePressGestureRecognizer' isn't defined for the class '#lib1::GestureDetector'.
I/flutter ( 2850): Try correcting the name to the name of an existing getter, or defining a getter or field named 'ForcePressGestureRecognizer'.
I/flutter ( 2850):       gestures[ForcePressGestureRecognizer] =
I/flutter ( 2850):                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
I/flutter ( 2850):       gestures[ForcePressGestureRecognizer] =
I/flutter ( 2850):                ^
I/flutter ( 2850): #0      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774:28)
I/flutter ( 2850): #1      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter ( 2850): #2      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2850): #3      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2850): Error caught by widgets library, thrown building GestureDetector(dirty).

**Comment by twovs** [comment]
这个插件需要 flutter 2.2.0+ 版本支持，flutter发行版1.x 会报上面的错误，经过很努力的尝试，终于将flutter升级到预览版了，所有的线索都在这个回答里，虽然刘成重新编辑了版本依赖的说明，但是并没有真正的支持到1.x

environment:
  - sdk: ">=2.1.0 <3.0.0"
 + sdk: ">=2.0.0 <3.0.0"   这是假的，哈哈哈
